### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by timpx** [ins-amu/scripts#5]

**Comment by timpx** [comment]
currently I see 3 kinds of tests:
- test of the wrapper of each node to check the command/script is correctly executed
- test of instantiating the pipeline to check connections
- test of particular results such as connected regions in the region mapping
Other ideas?

**Comment by maedoc** [comment]
> test of the wrapper of each node to check the command/script is correctly executed

This is responsibility of interface implementor, I would say, so only required if you've added new interfaces.

> test of instantiating the pipeline to check connections

This covers the workflow builder, and it's probably sufficient to check that in the graph, there are no cycles and the result nodes are reachable from the raw data nodes, i.e. path exists from raw T1 to resampled cortical surface.

> test of particular results such as connected regions in the region mapping

this is more difficult because ideally you'd have a data set with complete results to check against. if we can get a T1/DWI to demo the pipeline this could really be done.

**Comment by timpx** [comment]
done

**Comment by timpx** [comment]
done
