### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by timpx** [ins-amu/scripts#55]

**Comment by maedoc** [comment]
Stuff like this, you'd get for free if you based yours off our pipeline..  or you can just `FROM tvb/make`.

**Comment by timpx** [comment]
That's my intention, however it seems I will have to adapt your Dockerfile, since I want also ANTS. Or we agree on a docker file compatible both for tvb/make and script (which would probably be the best). I will get rid of the matlab dependency soon. BTW, anyway to get mrview working with docker?

**Comment by maedoc** [comment]
You can base your Docker image off ours with the from clause and then install Ants. Should be pretty easy. 

Graphics are less easy. I spent a few hours trying to get X11 working but it doesn't support GL well enough to be worthwhile, so the only way to make mrview et al work is via latest software GL drivers (mesa stack) and a VNC server. This is a major bémol but will hopefully improve as webgl based neuroimaging tools get better and we can just use a notebook with some widgets instead of a native app.

**Comment by maedoc** [comment]
Just had a chance to try out VMware Fusion 8 Pro... so it's a bit expensive but mrview works flawlessly so maybe we might try distributing VMware apps for interactive use and Docker image for just compute.

**Comment by timpx** [comment]
isn't it for Mac? At that point, I was thinking distributing the Docker image, and let the user install is own stuff via linux/virtual box/vmware if he wants mrview

**Comment by maedoc** [comment]
I think setting up ("provisioning" in dev ops parlance) is best handled by a set of Ansible scripts (at least that's the best tool I'm aware of) which would be flexible enough to handle the cluster, Docker image and a VMware machine.

The Fusion variant is mac specific but the machine format is generic and can be run by the free VMware Player (on windows or Linux).

It's worth spending time on this since people tend to want to work with 3D visualization tools which don't work in Docker (or on the cluster via X11 forward either)

**Comment by timpx** [comment]
Ok, I will probably let you do that in tvb-make though :)

**Comment by timpx** [comment]
done
