### ISSUE TITLE
 can not find "cmdremesher "in file cmdremesher

### ISSUE THREAD

**Issue by guiguiw** [ins-amu/scripts#66]
Hi, in scripts/main_surface.sh  line 273 ./remesher/cmdremesher/cmdremesher $PRD/surface/lh_high.off $PRD/surface/lh_low.off. I can not find "cmdremesher "in file cmdremesher, Could anyone tell me where I can find this file?
Thanks.

**Comment by guiguiw** [comment]
I have found a solution if somebody also needs help can go here: https://github.com/alextsui05/remesher
thanks.

**Comment by timpx** [comment]
Hi, sorry for the bug, I did a wrong commit a few weeks ago. I reverted the commit, could you try now and let me know if it works? About the remesher library, I would love to use this instead of having the code in the repo, the issue being that there were a number of fixed parameters I had to hard-code in the library. So I am curious, did you have success with this approach? If yes we should implement it.
